name: Build Linux-64 Static Libs
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    name: ${{ matrix.config.os }}
    runs-on: ${{ matrix.config.runs-on }}
    strategy:
      fail-fast: true
      matrix:
        config:
        - {
            distro: '20.04',
            runs-on: 'ubuntu-20.04'
          }
        - {
            distro: '18.04',
            runs-on: 'ubuntu-18.04'
          }
        - {
            distro: '16.04',
            runs-on: 'ubuntu-16.04'
          }
    steps:
      - name: Github Checkout Action to Authenticate the User
        uses: actions/checkout@master
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Apt Update and Installation of Essential Packages
        run: |
          sudo apt update -y
          #sudo apt upgrade -y
          sudo apt install -y git cmake git wget 
        shell: bash

      - name: Clone the master Branch of Repo
        id: clone-master-branch
        run: |
          git clone https://github.com/beyond-all-reason/spring-static-libs.git -b master spring-static-libs-scripts
          echo "::set-output commit-id=$(git rev-parse --short HEAD)"
          git clone https://github.com/beyond-all-reason/spring-static-libs.git -b ${{ matrix.config.distro }} spring-static-libs
        shell: bash

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - name: Execute install-linux.sh
        run: |
          sudo ./_scripts/install-linux.sh /spring-static-libs
        working-directory: ${{ github.workspace }}/spring-static-libs-scripts
        shell: bash

      - name: Execute make_static_libs.sh
        run: |
          sudo ./_scripts/make_static_libs.sh /spring-static-libs
        working-directory: ${{ github.workspace }}/spring-static-libs-scripts
        shell: bash

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ./*
          git commit -m "Github Action Build of ${{ steps.clone-master-branch.outputs.commit-id }}"
        working-directory: ${{ github.workspace }}/spring-static-libs
        shell: bash

      - name: Push Changes to ${{ matrix.config.distro }} Branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ matrix.config.distro }}
          directory: ${{ github.workspace }}/spring-static-libs